apiVersion: v2
name: srv-grpc
description: Grpc example
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: common
    version: 1.0.0
    repository: file://../../deploy/kube/helm/common