apiVersion: v1
kind: Service
metadata:
  namespace: {{.Release.Namespace}}
  name: {{ .Chart.Name }}-api
  labels:
    app: {{ .Chart.Name }}-api
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name }}-api
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      protocol: TCP
